<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.ditto-chat</groupId>
	<artifactId>ditto-chat-server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ditto-chat-server</name>
	<description>Ditto Chat Server</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>25</java.version>
		<querydsl.version>5.0.0</querydsl.version>
	</properties>
	<dependencies>
		<dependency>
			<!-- Enables configuring SpringApplication -->
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<dependency>
			<!-- Enables usage of JPA and Hibernate -->
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<!-- Implements DataSource Interface and enables establishment of JDBC Connections -->
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<!-- Enables Running Flyway Migrations on MySQL Databases -->
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-mysql</artifactId>
		</dependency>

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency> -->



		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency> -->

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-session-data-redis</artifactId>
		</dependency> -->
	

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator-test</artifactId>
			<scope>test</scope>
		</dependency> -->

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa-test</artifactId>
			<scope>test</scope>
		</dependency> -->

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security-test</artifactId>
			<scope>test</scope>
		</dependency> -->

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-session-data-redis-test</artifactId>
			<scope>test</scope>
		</dependency> -->
		
		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency> -->

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency> -->

		<!-- <dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency> -->

		<!-- <dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>${querydsl.version}</version>
			<classifier>jakarta</classifier>
			<scope>provided</scope>
		</dependency> -->

		<!-- <dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
			<version>${querydsl.version}</version>
			<classifier>jakarta</classifier>
		</dependency> -->

		<!-- NOTE: needed to run migrations on application start -->
		<!-- <dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency> -->

		<!-- <dependency> -->
			<!-- Enables exposing Metrics in Prometheus format. Following Documentation at: https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.getting-started and https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints -->
			<!-- <groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<version>1.17.0-RC1</version>
		</dependency> -->

		<!-- Importing only used AWS SDK Modules per suggestion at https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/get-started.html -->
		<!-- <dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3</artifactId>
			<version>2.47.4</version> -->
			<!-- Use the latest version available -->
		<!-- </dependency> -->
	</dependencies>

	<build>
		<plugins>
			<!-- <plugin> -->
				<!-- Following Documentation at: http://querydsl.com/static/querydsl/5.0.0/reference/html_single/ and guide at https://www.baeldung.com/intro-to-querydsl -->
				<!-- <groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<version>1.1.3</version>
				<executions>
					<execution>
					<goals>
						<goal>process</goal>
					</goals>
					<configuration>
						<outputDirectory>target/generated-sources/java</outputDirectory>
						<processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
					</configuration>
					</execution>
				</executions>
			</plugin> -->
			<!-- <plugin> -->
				<!-- This plugin is needed since Spring Boot application needs to be packaged in a specific way. -->
				<!-- Enables mvn spring-boot:run Command https://docs.spring.io/spring-boot/maven-plugin/run.htm -->
				<!-- <groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin> -->
			<!-- <plugin> -->
				<!-- Plugin used during mvn test. Enables generating surefire Test Reports -->
				<!-- Documentation at: https://maven.apache.org/surefire/maven-surefire-plugin/index.html -->
				<!-- <groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.5</version>
				<configuration> -->
					<!-- Documentation at: https://maven.apache.org/surefire/maven-surefire-report-plugin/report-mojo.html -->
					<!-- <outputDirectory>${project.basedir}/surefire-test-reports</outputDirectory>
				</configuration>
			</plugin> -->
			<plugin>
				<!-- Documentation at: https://documentation.red-gate.com/fd/maven-goal-277579365.html -->
				<!-- Plugin used to run and rollback migrations within Pipeline -->
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-maven-plugin</artifactId>
				<version>12.10.0</version>
				<configuration>
					<url>jdbc:mysql://ditto-chat-db-server:3306/ditto_chat_db</url>
					<user>ditto_chat_server</user>
					<password>ditto_chat_server_pasZword</password>
					<locations>
						<location>classpath:db/migration</location>
					</locations>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
