spring.application.name=ditto-chat-server
server.port=${DITTO_CHAT_SERVER_HTTP_PORT}

# Client Application reference
client.domain=${DITTO_CHAT_CLIENT_DOMAIN}

logging.config=classpath:logger/logback-local.xml
logging.level.com.zaxxer.hikari=TRACE

# Redis Cache Configuration
spring.data.redis.host=${DITTO_CHAT_REDIS_HOST}
spring.data.redis.port=${DITTO_CHAT_REDIS_PORT}
spring.data.redis.timeout=5s
spring.cache.redis.time-to-live=24h
# spring.data.redis.ssl.enabled=true    TODO-prod: needs to be set in Production! SSL/TLS is used Remotely, but not used Locally!
server.servlet.session.timeout=1800s

# configuration required to use SMTP gmail server
spring.mail.host=${DITTO_CHAT_MAIL_HOST}
spring.mail.port=${DITTO_CHAT_MAIL_PORT}
spring.mail.username=${DITTO_CHAT_MAIL_USERNAME}
spring.mail.password=${DITTO_CHAT_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
