spring.application.name=ditto-chat-server
server.port=${DITTO_CHAT_SERVER_HTTP_PORT}

# TODO-logger: Test it
# logging.config=classpath:/logger/logback-local.xml
# logging.level.com.zaxxer.hikari=TRACE

# Redis Cache Configuration
spring.data.redis.host=${DITTO_CHAT_REDIS_HOST}
spring.data.redis.port=${DITTO_CHAT_REDIS_PORT}
spring.data.redis.timeout=5s
spring.cache.redis.time-to-live=24h
# spring.data.redis.ssl.enabled=true    TODO: needs to be set in Production! SSL/TLS is used Remotely, but not used Locally!
server.servlet.session.timeout=1800s
