const CONSTANTS = {
    COMPANY_URL: "https://ditto-consulting.com",
    APPLICATION_NAME: "DittoChat",

    ROOT_URL: "/",
    REGISTER_URL: "/register",
    LOGIN_URL: "/login",
    LOGOUT_URL: "/logout",
    FORGOT_PASSWORD_URL: "/forgot-password",
    RESET_PASSWORD_URL: "/reset-password",
    HOME_URL: "/home",
    CHATS_URL: "/chats",
    CHATTERS_URL: "/chatters",
    ACCOUNT_URL: "/account",
    REQUEST_UPLOAD_FILE_URL: "/request-upload-file-url",
    CHAT_URL: "/chat",
    GET_LATEST_CHAT_MESSAGES_URL: "/get-latest-messages",
    UPDATE_LAST_SEEN_CHAT_MESSAGE_URL: "/update-last-seen-message",
    SEND_CHAT_MESSAGE_URL: "/send-message",
    CLEAR_CHAT_HISTORY_URL: "/clear-history",
    CHATTER_URL: "/chatter",
    CHATTER_SHARED_FILES: "/shared-files",

    NUMBER_OF_ITEMS_PER_PAGE: 10,
    ICON_SIZE: 26,
    LARGER_ICON_SIZE: 30,
    SEARCH_FILTER_CHANGE_HTTP_REQUEST_DELAY_IN_MS: 300,
    CHAT_POLLING_INTERVAL_IN_MS: 10000,
    CONTENT_TYPE_STREAM: "application/octet-stream",

    INPUT_FILE_TYPE_PDF: "application/pdf",
    INPUT_FILE_TYPE_TEXT: "text/plain",
    INPUT_FILE_TYPE_PNG: "image/png",
    INPUT_FILE_TYPE_JPEG: "image/jpeg",

    SEARCH_FILTER_QUERY_PARAMETER: "searchFilter",
    PAGE_NUMBER_QUERY_PARAMETER: "pageNumber",
    IS_INITIAL_RETRIEVAL_QUERY_PARAMETER: "isInitialRetrieval",
    IS_POLLING_QUERY_PARAMTER: "isPolling",
    PASSWORD_RESET_TOKEN_QUERY_PARAMETER: "passwordResetToken",

    INVALID_NAME_INPUT_CLIENT_MESSAGE: "Name must be at least 2 characters long",
    INVALID_SURNAME_INPUT_CLIENT_MESSAGE: "Surname must be at least 2 characters long",
    INVALID_USERNAME_INPUT_CLIENT_MESSAGE: "Username must be at least 6 characters long",
    INVALID_EMAIL_INPUT_CLIENT_MESSAGE: "Please provide a valid Email",
    INVALID_PASSWORD_INPUT_CLIENT_MESSAGE: "Password must be at least 6 characters long",
    INVALID_REPEATED_PASSWORD_INPUT_CLIENT_MESSAGE: "Passwords do not match",

    CTA_BUTTON_CONTACT_US_LABEL: "Contact Us",
    CTA_BUTTON_LOGIN_LABEL: "Log In",
    CTA_BUTTON_REGISTER_LABEL: "Register",
    CTA_BUTTON_SUBMIT_LABEL: "Submit",
}

export default CONSTANTS;
